/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package foo;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class LibraryTest {

  @Test
  public void testSomeLibraryMethod() {
    Library library = null;
    assertTrue("someLibraryMethod should return 'true'", library.someLibraryMethod());
  }
}
